---
version: "2.0"

services:
  cron:
    image: tombeynon/akash-postgres-restore:v0.0.1
    env:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=postgres-restore
      - BACKUP_PATH=mybucket
      - BACKUP_KEY=KEY
      - BACKUP_SECRET=SECRET
      - BACKUP_PASSPHRASE=passphrase
    depends_on:
      - service: postgres
  postgres:
    image: postgres:12.6
    env:
      - POSTGRES_PASSWORD=password
    expose:
      - port: 5432
        proto: tcp
        to:
          - global: true
          - service: cron

profiles:
  compute:
    cron:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 1Gi
        storage:
          size: 1Gi
    postgres:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 1Gi
        storage:
          size: 1Gi
  placement:
    dcloud:
      pricing:
        cron:
          denom: uakt
          amount: 10
        postgres:
          denom: uakt
          amount: 10

deployment:
  cron:
    dcloud:
      profile: cron
      count: 1
  postgres:
    dcloud:
      profile: postgres
      count: 1
