version: '3.4'

services:
  scheduler:
    build:
      context: .
    volumes:
      - ./scripts:/scripts
      - ./crontab:/crontab
    depends_on:
      - postgres
    env_file: .env

  postgres:
    image: postgres:12.6
    ports:
      - "5432:5432"
    env_file: .env
